services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: devops_project
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  user-service:
    build: ./src/user-service
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops_project
      - JWT_SECRET=supersecretjwtkey
      - PORT=5000
    restart: unless-stopped

  product-service:
    build: ./src/product-service
    container_name: product-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops_project
      - PORT=5001
    restart: unless-stopped

  order-service:
    build: ./src/order-service
    container_name: order-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops_project
      - PORT=5002
    restart: unless-stopped

  notification-service:
    build: ./src/notification-service
    container_name: notification-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops_project
      - PORT=5003
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  mongo_data:
